services:
  backend:
    depends_on:
      - sql
    image: backend
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT : "Development"
    ports:
      - "80:8080"

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "VerstaTest123"
    ports:
      - "1433:1433"

  frontend:
    image: frontend
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"