version: '3.4'

services:
  webapplication2:
    image: ${DOCKER_REGISTRY-}webapplication2
    build:
      context: .
      dockerfile: WebApplication2/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
  client:
    image: client
    build:
      context: ./my-app
      dockerfile: Dockerfile
  proxy:
    image: nginx:mainline